version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_PASSWORD: dev
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
